AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for sam-app

Globals:
    Function:
      Runtime: java8
      Timeout: 20
      MemorySize: 512

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./target/aws-serverless-with-sam-0.0.1-SNAPSHOT.jar
      Handler: com.example.awsserverlessdemo.HelloWorldHandler::handleRequest
      #Policies: AWSLambdaBasicExecutionRole
      Role: arn:aws:iam::881914528194:role/OrderManagementLambdaExecutionRole
      Events:
        GreetWorld:
          Type: Api
          Properties:
            Path: /hello-world
            Method: get